### ISSUE TITLE
Error "draw: decode[E] image: The system cannot find the file specified. (os error 2)" even when file name is explicitly set

### ISSUE THREAD

**Issue by devins2518** [AbsurdlySuspicious/sg-sprite#3]
![Capture](https://user-images.githubusercontent.com/17111639/87821552-a24d0580-c835-11ea-9672-f054f3fb81de.PNG)
I'm encountering this error when trying to unpack a folder full of .lay sprites from [this game](https://nopaystation.com/view/PSV/PCSG00895/OREGAIRUZOKUVITA/1?version=1.01). The same thing happens when I explicitly say the file name as well. I'm not even going to pretend I understand how to unpack .lay files but a .gxt file close to the same name was in the original .mpk dump so I thought that it needed to be referenced or something. The same error happens with and without the .gxt. All of the lay files have the same `25 00 00 00` file signature when I open them with a hex editor so I think it is in the actual .lay format. Any help would be appreciated.

**Comment by AbsurdlySuspicious** [comment]
This tool tries to find png with actual sprite chunks with the same name as lay file and doesn't know anything about gxt. Perhaps this game uses some different file layout compared to sciadv series. I will try to investigate this

**Comment by devins2518** [comment]
Thank you, heres a link to the lay file I was trying to unpack, hopefully it'll shed some more light to this issue. https://filebin.net/wo5jjuxmvfwtjz2h

**Comment by AbsurdlySuspicious** [comment]
Lay files are perfectly normal but gxt files are seem to be ~~some zlib compressed in-house bitmap/image format and will require some reversing. I will look into this~~
EDIT: nope, these are standard vita texture files

**Comment by AbsurdlySuspicious** [comment]
Check the latest release and new FAQ in README. Should work now
Feel free to write here if you have any problems with this

**Comment by devins2518** [comment]
~~I'm getting some different errors now. `thread 'main' panicked at 'Can't canonicalize .lay path: Os { code: 123, kind: Other, message: "The filename, directory name, or volume label syntax is incorrect." }', src/main.rs:122:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace` when using any commands with *.lay and `[E] No corresponding png file
[E] (EBI_LAC_.lay)` when using an explicit file name~~
Nevermind, the GXT output files had slightly different names so they weren't being recognized, it works now after manually editing file names. Thanks so much!
