### ISSUE TITLE
overlay image only functionality

### ISSUE THREAD

**Issue by kedarguru** [AbsurdlySuspicious/sg-sprite#4]
I'm not sure how to best word this so I'll do it by example - instead of a sprite set of Daru with the nosebleed images superimposed, can you output just the nosebleed image sequence separately? I don't know how you feel about this, but for me it'll be useful to have a way to output an overlay from your script even if I have to position it myself.

**Comment by kedarguru** [comment]
I realized that Nimms script is capable of this, so I can use it as an alternative:
https://gist.github.com/drdaxxy/6f60d2022035ebf9f3ffd4cd56a94b9e

Still, there are limitations with that script as compared with yours, so I would rather not rely on it if I had a choice.

**Comment by AbsurdlySuspicious** [comment]
Good idea. I'll work on it today (I hope)

**Comment by kedarguru** [comment]
Great! One last clarification - I found that Nimms script will output the nosebleed images with a transparent border so as to be the same dimensions as Daru's image. You can layer the two images very conveniently this way. This is more useful than, say, a tiny image which is just the nosebleed itself.

**Comment by AbsurdlySuspicious** [comment]
https://github.com/AbsurdlySuspicious/sg-sprite/releases/tag/0.3.0
